/* Сгенерировано tools/import-texts.cjs из 12-teksty-opisaniya.md + служебные строки интерфейса страницы, не из файла копирайтера (page_title, ui_lang, ui_theme, ui_theme_system, ui_theme_light, ui_theme_dark, ui_module, ui_step, ui_home, meta_desc). Руками не править. */
(function (root) {
  var T = {
  "ru": {
    "hero_eyebrow": "Система для застройщика вилл",
    "h1": "Виллы, магазин и консьерж в одной системе",
    "lead": "Покупатель следит за стройкой и платежами на своём языке. Вы видите три бизнеса в одних цифрах.",
    "demo_note": "Villa Group и проект Hillside 19 — названия для демо. В вашей системе будут ваши проекты и ваши данные.",
    "header_demo": "Демо",
    "topbar_name": "demda.pro · система для застройщика",
    "biz_build": ["Застройка","Виллы на продажу"],
    "biz_shop": ["Магазин","Мебель и отделка"],
    "biz_service": ["Консьерж","Трансфер, уборка, ремонт"],
    "pain_title": "Три бизнеса, одни и те же клиенты",
    "pain_text": "Человек покупает у вас виллу. Потом заказывает в вашем магазине мебель и отделку. После передачи ключей пишет консьержу: встретить в аэропорту, убрать дом, починить кондиционер.\n\nКогда у застройщика растут сразу три бизнеса, сведения о клиенте копятся в разных местах. Платежи лежат в таблице, фото со стройки в переписке, заявки консьержу в телефоне диспетчера. Система собирает всё это в одну карточку клиента. Из тех же данных складывается отчёт для вас и для инвесторов.",
    "modules_title": "Из чего состоит система",
    "m1_title": "Лоты и продажи",
    "m1_text": "Все виллы проекта на одной схеме: свободна, бронь, продана и сколько построено. У каждого покупателя карточка с графиком платежей по этапам стройки. Сразу видно, какой платёж следующий и какой просрочен. Сделки идут по воронке, от первого звонка до договора. По каждому клиенту записано, кто его привёл: агент, сайт, рекомендация или партнёр в Китае.",
    "m2_title": "Кабинет покупателя и инвестора",
    "m2_text": "Покупатель открывает ссылку и видит свою виллу. Там этапы стройки с фото и отчётами, сколько оплачено и сколько осталось, договоры и акты. Кабинет работает на русском, английском и китайском, язык покупатель выбирает сам. Инвестор видит сводку по всему проекту: сколько вилл продано, сколько денег пришло, на каком этапе стройка.",
    "m3_title": "Консьерж",
    "m3_text": "Владелец виллы оставляет заявку: встреча в аэропорту, трансфер, уборка, ремонт. Диспетчер назначает исполнителя и видит, сколько времени заявка ждёт ответа. Переписка переводится сама. Владелец пишет по-русски или по-китайски, исполнитель читает по-тайски. Когда работа сделана, владелец получает счёт.",
    "m4_title": "Магазин мебели и отделки",
    "m4_text": "Магазин работает как отдельный бизнес. В каталоге отделка, сантехника, кухни, мебель, свет и текстиль. По каждой позиции видно, сколько лежит на складе и что везут под заказ. Цены две: розничная и для партнёров. Заказы трёх видов: на ваши стройки, от других застройщиков и подрядчиков, от покупателей и владельцев вилл. У каждой поставки свой срок, выручка считается по каждому виду заказов. Покупатель виллы выбирает отделку прямо в своём кабинете, и заказ сразу попадает в магазин.",
    "m5_title": "Сводка группы",
    "m5_text": "Экран владельца: три бизнеса в одних цифрах. Сколько вилл продано и сколько денег пришло. Какие платежи просрочены. Сколько за месяц заработали консьерж и магазин. Отдельно видно, сколько каждый клиент принёс всем трём бизнесам. Суммы показываются в батах, долларах или юанях.",
    "caption_1": "Лоты. Все 19 вилл Hillside 19 на одной схеме. Цвет показывает статус, полоса показывает, сколько построено.",
    "caption_2": "Кабинет покупателя на китайском. Этапы стройки с фото, оплачено и осталось, договоры и акты.",
    "caption_3": "Консьерж. Владелец пишет по-русски, диспетчер видит перевод на тайский. Таймер показывает, сколько заявка ждёт ответа.",
    "caption_4": "Магазин. Заказы своих строек, подрядчиков и покупателей в одном списке. У каждой позиции видно склад и срок поставки.",
    "caption_5": "Сводка группы. Стройка, продажи, консьерж и магазин на одном экране. Суммы в батах, долларах или юанях.",
    "caption_link": "Открыть этот экран",
    "roles_title": "Каждый видит своё",
    "roles_text": "Покупатель видит только свою виллу. Инвестор получает сводку по проекту. Менеджер продаж работает с виллами, сделками и платежами, диспетчер консьержа с заявками. Владелец видит всё. В демо роли переключаются кнопкой «Смотреть как»: Партнёр (это владелец), Продажи, Покупатель, Консьерж. Сводки инвестора в демо пока нет, она входит в первую версию.",
    "journey_title": "Что видит покупатель от брони до ключей",
    "journey_1": "Покупает виллу. Менеджер ставит бронь, и вилла на схеме становится занятой. Покупатель получает ссылку на свой кабинет.",
    "journey_2": "Следит за стройкой на своём языке. У каждого этапа фото и короткий отчёт. Покупатель из Шанхая читает по-китайски, из Москвы по-русски.",
    "journey_3": "Платит по этапам. В кабинете видно, сколько платить дальше и до какого числа. Деньги пришли — менеджер отмечает платёж, и в кабинете появляется квитанция. Сами деньги идут как сейчас: система их не принимает, она показывает график.",
    "journey_4": "Выбирает отделку и мебель в вашем магазине. Варианты берёт из каталога, смета пересчитывается сразу. Заказ уходит в магазин и привязан к его вилле.",
    "journey_5": "Получает ключи и пользуется консьержем. Встречу в аэропорту, уборку перед приездом и мелкий ремонт заказывает из того же кабинета.",
    "about_title": "Систему делает студия demda.pro",
    "about_text": "Мы студия заказной разработки. Основатель студии Дмитрий Демченко работает с SAP с 2012 года. Вот что уже работает из сделанного нами.",
    "about_fact_1": "MyPulso, наш сервис для поиска персонального тренера. Приложения клиента и тренера опубликованы в App Store и Google Play.",
    "about_fact_2": "Система для прокатной компании. Заказы приходят сами из внешней системы бронирования. В админке заказы, финансовый журнал и отчёты. Бот рассылает уведомления по ролям, у водителей своё приложение в App Store и Google Play. Система в боевой эксплуатации.",
    "about_fact_3": "Maketa, наш конструктор экранов приложения. Открыт для всех на maketa.pro.",
    "about_link": "Подробнее о студии на demda.pro",
    "process_title": "Как пойдёт работа",
    "process_steps": ["Берём один ваш проект. Нужны список вилл, графики оплат и несколько фото со стройки. Разбираемся, как вы продаёте сейчас и кто что должен видеть.","Через две недели после получения данных показываем первые экраны. На них ваши виллы, ваши покупатели и ваши платежи. После показа считаем цену первой версии.","Первая версия, на которой можно работать, готова через 8 недель от начала. В неё входят лоты, продажи и кабинет покупателя и инвестора на трёх языках. Китайские тексты кабинета до запуска вычитывает носитель языка.","Потом подключаем консьержа и магазин. Они встают на ту же базу клиентов и вилл, переделывать ничего не придётся. Сроки по ним назовём после первой версии."],
    "process_note": "Систему ставим на сервер в Азии. Сервер ваш, данные тоже ваши.",
    "cta_title": "Откройте демо и покажите партнёрам",
    "cta_text": "В демо работает каждая кнопка. Можно поставить бронь, отметить платёж, переключить кабинет на китайский, собрать заказ в магазине. Данные выдуманы, демо можно сбросить в любой момент.",
    "cta_button": "Открыть демо",
    "contact": "Дмитрий Демченко, основатель demda.pro. Telegram @demda, почта hello@demda.pro. Пришлите один проект, и через две недели покажем его в системе.",
    "og_title": "Виллы, магазин и консьерж в одной системе",
    "og_description": "Покупатель следит за стройкой и платежами на своём языке. Владелец видит три бизнеса в одних цифрах. Демо на русском, английском и китайском.",
    "demo_about": "О системе",
    "demo_contact": "Написать нам",
    "footer_note": "Прототип demda.pro. Названия компаний, имена людей и цифры вымышлены. Фото взяты из открытых фотобанков и не изображают реальные объекты.",
    "footer_credits": "Авторы фото",
    "alt_d_hero": "Готовая вилла с плоской кровлей и бассейном на склоне холма, вокруг тропическая зелень",
    "alt_d_biz_build": "Стройка виллы: стена с арматурой на фоне тропической зелени",
    "alt_d_biz_shop": "Шоурум отделки и мебели: стенд с образцами плитки и камня, диван и светильник",
    "alt_d_biz_service_maid": "Горничная заправляет кровать в спальне виллы",
    "alt_d_biz_service_driver": "Водитель держит ключи у машины",
    "alt_d_biz_service_minivan": "Минивэн с открытой дверью у терминала аэропорта",
    "alt_d_interior": "Гостиная готовой виллы с выходом на террасу и бассейн, отделка из дерева и камня",
    "alt_d_warehouse": "Склад магазина: стеллажи с коробками и паллеты с плиткой",
    "alt_frame_1": "Экран «Лоты» в демо: 19 вилл проекта Hillside 19, у каждой статус и полоса готовности стройки",
    "alt_frame_2": "Кабинет покупателя на китайском: этапы стройки с фото, сколько оплачено и сколько осталось",
    "alt_frame_3": "Заявка К-118 в консьерже: встреча в аэропорту, переписка с владельцем и перевод сообщений",
    "alt_frame_4": "Экран «Заказы» магазина: заказы трёх каналов со статусом, суммой и сроком поставки",
    "alt_frame_5": "Сводка группы в демо: продажи вилл, поступления, консьерж и магазин на одном экране",
    "page_title": "Villa Group · система для застройщика: описание",
    "ui_lang": "Язык",
    "ui_theme": "Тема",
    "ui_theme_system": "Как в системе",
    "ui_theme_light": "Светлая",
    "ui_theme_dark": "Тёмная",
    "ui_module": "Модуль",
    "ui_step": "Шаг",
    "ui_home": "demda.pro, наверх",
    "meta_desc": "Villa Group: описание системы для застройщика на Пхукете. Лоты и продажи, кабинет покупателя, консьерж, магазин, сводка партнёра."
  },
  "en": {
    "hero_eyebrow": "A management system for villa developers",
    "h1": "Villa sales, a furniture store and concierge in one system",
    "lead": "Buyers follow construction and payments in their own language. Investors see where the project stands. The owner sees all three businesses in one set of numbers.",
    "demo_note": "Villa Group and Hillside 19 are demo names. The real system runs on the developer's own projects and data.",
    "header_demo": "Demo",
    "topbar_name": "demda.pro · a system for villa developers",
    "biz_build": ["Construction","Villas for sale"],
    "biz_shop": ["Store","Furniture and finishes"],
    "biz_service": ["Concierge","Pickups, cleaning, repairs"],
    "pain_title": "Three businesses, the same clients",
    "pain_text": "A client buys a villa. Later they order furniture and finishes from the group's store. After handover they contact the concierge: an airport pickup, cleaning, a broken air conditioner.\n\nWhen a developer grows three businesses at once, client information builds up in different places. Payments sit in a spreadsheet, site photos in message threads, concierge requests on the dispatcher's phone. The system brings all of it into one client record. The same data feeds the reports for the owner and for investors.",
    "modules_title": "Five parts of one system",
    "m1_title": "Villas and sales",
    "m1_text": "Every villa in the project on one plan: available, reserved or sold, and how far construction has gone. Each buyer has a record with a payment schedule tied to construction stages. The next payment and any overdue ones are visible at once. Deals move from the first enquiry to a signed contract. Each client's source is recorded: an agent, the website, a referral or a partner in China.",
    "m2_title": "Buyer portal and investor view",
    "m2_text": "A buyer opens a link and sees their own villa: construction stages with photos and reports, what has been paid and what is still due, contracts and stage acceptance certificates. The portal works in Russian, English and Chinese, and each buyer picks the language. Investors get a view of the whole project: villas sold, money received, the current construction stage.",
    "m3_title": "Concierge",
    "m3_text": "A villa owner sends a request: airport pickup, transfer, cleaning or repairs. The dispatcher assigns a staff member and sees how long the request has been waiting. Messages are translated automatically. The owner writes in Russian or Chinese, and the staff member reads it in Thai. When the job is done, the owner receives an invoice.",
    "m4_title": "Furniture and finishing materials store",
    "m4_text": "The store runs as a business of its own. The catalogue covers finishes, plumbing, kitchens, furniture, lighting and textiles. For every item you see what is in stock and what is on order. There are two price lists, retail and trade. Orders come in three kinds: for the group's own sites, from other developers and contractors, and from buyers and villa owners. Every delivery has a date, and revenue is tracked for each kind of order. A villa buyer can choose finishes right in the portal, and the order goes straight to the store.",
    "m5_title": "Group overview",
    "m5_text": "The owner's screen for all three businesses. Villas sold and money received. Overdue payments. What the concierge and the store earned this month. What each client has brought to all three businesses. Amounts in Thai baht, US dollars or Chinese yuan.",
    "caption_1": "Villas. All 19 villas of Hillside 19 on one plan. Colour shows the status, the bar shows construction progress.",
    "caption_2": "Buyer portal in Chinese. Construction stages with photos, paid and outstanding amounts, contracts and certificates.",
    "caption_3": "Concierge. The owner writes in Russian, the dispatcher sees it translated into Thai. A timer shows how long the request has been waiting.",
    "caption_4": "Store. Orders from the group's sites, contractors and buyers in one list. Stock and delivery date for every item.",
    "caption_5": "Group overview. Construction, sales, concierge and store on one screen. Amounts in baht, dollars or yuan.",
    "caption_link": "Open this screen",
    "roles_title": "Everyone sees their own part",
    "roles_text": "A buyer sees only their own villa. An investor gets the project view. Sales managers work with villas, deals and payments, and the concierge dispatcher works with requests. The business owner sees everything. In the demo, the ‘View as’ switch shows four roles: Partner (the owner), Sales, Buyer and Concierge. The investor view is part of the first version and is not in the demo yet.",
    "journey_title": "What a buyer sees, from reservation to keys",
    "journey_1": "Buys a villa. The sales manager records the reservation, and the villa shows as taken on the plan. The buyer gets a link to their portal.",
    "journey_2": "Follows construction in their own language. Every stage has photos and a short report. A buyer from Shanghai reads it in Chinese, a buyer from Moscow in Russian.",
    "journey_3": "Pays stage by stage. The portal shows the next amount and the due date. Once the money arrives, the manager records the payment and a receipt appears in the portal. Payments are made the same way as today. The system doesn't handle money, it shows the schedule.",
    "journey_4": "Chooses finishes and furniture from the group's store. Options come from the catalogue, and the estimate updates instantly. The order goes to the store, linked to the buyer's villa.",
    "journey_5": "Gets the keys and uses the concierge. Airport pickup, cleaning before arrival and small repairs are booked from the same portal.",
    "about_title": "Built by demda.pro",
    "about_text": "demda.pro is a custom software studio. The founder, Dmitry Demchenko, has worked with SAP since 2012. Here is some of our work that is already in use.",
    "about_fact_1": "MyPulso, our own service for finding a personal trainer. The client app and the trainer app are live on the App Store and Google Play.",
    "about_fact_2": "An operations system for a rental company. Orders arrive automatically from an external booking system. The admin panel covers orders, a financial ledger and reports. A bot sends notifications by role, and drivers have their own app on the App Store and Google Play. The system is in production use.",
    "about_fact_3": "Maketa, our app screen builder. It is open to everyone at maketa.pro.",
    "about_link": "More about the studio at demda.pro",
    "process_title": "How the work goes",
    "process_steps": ["We start with one project. We need the villa list, payment schedules and a few site photos. We look at how sales work today and who needs to see what.","Two weeks after we receive the data, we show the first screens with the developer's real villas, buyers and payments. The price of the first version is set after that review.","The first working version is ready eight weeks from the start. It covers villas, sales, and the buyer portal and investor view in three languages. A native speaker proofreads the Chinese text before launch.","Then we add the concierge and the store. They use the same client and villa data, so nothing has to be rebuilt. Their timeline is set once the first version is done."],
    "process_note": "The system runs on a server in Asia. The server and the data belong to the developer.",
    "cta_title": "Try the demo",
    "cta_text": "Every button in the demo works. Reserve a villa, record a payment, switch the buyer portal to Chinese, create a store order. All data is fictional, and the demo can be reset at any time.",
    "cta_button": "Open the demo",
    "contact": "Dmitry Demchenko, founder of demda.pro. Telegram @demda, email hello@demda.pro. Send us one project, and two weeks later we'll show it in the system.",
    "og_title": "Villa sales, a furniture store and concierge in one system",
    "og_description": "Buyers follow construction and payments in their own language. Investors see where the project stands. Demo in English, Russian and Chinese.",
    "demo_about": "About the system",
    "demo_contact": "Contact us",
    "footer_note": "A demda.pro prototype. Company names, people and figures are made up. Photos come from free stock libraries and do not show real properties.",
    "footer_credits": "Photo credits",
    "alt_d_hero": "Finished villa with a flat roof and a pool on a hillside, surrounded by tropical greenery",
    "alt_d_biz_build": "Villa under construction: a wall with exposed rebar against tropical greenery",
    "alt_d_biz_shop": "Finishes and furniture showroom: a stand of tile and stone samples, a sofa and a lamp",
    "alt_d_biz_service_maid": "Housekeeper making the bed in a villa bedroom",
    "alt_d_biz_service_driver": "Driver holding the car keys next to the car",
    "alt_d_biz_service_minivan": "Minivan with an open door outside the airport terminal",
    "alt_d_interior": "Living room of a finished villa opening onto a terrace and pool, with wood and stone finishes",
    "alt_d_warehouse": "Store warehouse: shelves of boxes and pallets of tiles",
    "alt_frame_1": "Villas screen in the demo: the 19 villas of Hillside 19, each with its status and construction progress bar",
    "alt_frame_2": "Buyer portal in Chinese: construction stages with photos, amount paid and amount outstanding",
    "alt_frame_3": "Concierge request K-118: airport pickup, chat with the owner and message translation",
    "alt_frame_4": "Store orders screen: orders from three channels with status, amount and delivery date",
    "alt_frame_5": "Group overview in the demo: villa sales, money received, concierge and store on one screen",
    "page_title": "Villa Group · a system for developers: overview",
    "ui_lang": "Language",
    "ui_theme": "Theme",
    "ui_theme_system": "Match system",
    "ui_theme_light": "Light",
    "ui_theme_dark": "Dark",
    "ui_module": "Module",
    "ui_step": "Step",
    "ui_home": "demda.pro, back to top",
    "meta_desc": "Villa Group: an overview of a system for a Phuket developer. Units and sales, buyer portal, concierge, store, partner dashboard."
  },
  "zh": {
    "hero_eyebrow": "面向别墅开发商的管理系统",
    "h1": "别墅销售、家居建材店和礼宾服务，用一个系统管理",
    "lead": "买家用自己的语言查看施工进度和付款情况。投资人随时了解项目进展。业主在同一组数据中掌握三项业务。",
    "demo_note": "Villa Group 和 Hillside 19 为演示名称。正式系统将使用开发商自己的项目和数据。",
    "header_demo": "演示",
    "topbar_name": "demda.pro · 别墅开发商管理系统",
    "biz_build": ["别墅开发","在售别墅"],
    "biz_shop": ["家居建材店","家具与装修材料"],
    "biz_service": ["礼宾服务","接送、清洁、维修"],
    "pain_title": "三项业务，同一批客户",
    "pain_text": "客户买下一栋别墅。之后，他在集团的店里订购家具和装修材料。交房后，他联系礼宾服务：机场接机、打扫房屋、修理空调。\n\n当开发商同时发展三项业务时，客户信息往往分散在不同地方：付款记在表格里，工地照片在聊天记录中，礼宾需求在调度员的手机上。系统把这些信息汇总到一张客户卡片里。业主和投资人的报表也来自同一份数据。",
    "modules_title": "系统的五个部分",
    "m1_title": "房源与销售",
    "m1_text": "项目中的所有别墅显示在一张平面图上：可售、已预订、已售出，以及施工进度。每位买家都有一张客户卡，附有按施工阶段划分的付款计划。下一笔付款和逾期付款一目了然。交易按销售流程推进，从第一次咨询到签订合同。每位客户的来源都有记录：中介、网站、熟人推荐或中国合作伙伴。",
    "m2_title": "买家账户与投资人视图",
    "m2_text": "买家打开链接，就能看到自己的别墅：各施工阶段的照片和报告、已付和待付金额、合同和阶段验收单。账户支持中文、英文和俄文，买家可自行选择。投资人可以查看整个项目的汇总：已售出多少栋、到账多少资金、施工进行到哪个阶段。",
    "m3_title": "礼宾服务",
    "m3_text": "业主提交需求：机场接机、接送、清洁、维修。调度员指派工作人员，并能看到需求已经等待了多久。对话自动翻译：业主用中文或俄文书写，工作人员看到的是泰文。服务完成后，业主收到账单。",
    "m4_title": "家具与装修材料店",
    "m4_text": "店铺作为一项独立业务运营。商品目录包括装修材料、卫浴、厨房、家具、灯具和布艺。每件商品都能看到现有库存和在途订货。价格分为零售价和合作伙伴价。订单分三类：集团自己的工地、外部开发商和施工方、买家和别墅业主。每批供货都有明确日期，收入按订单类型分别统计。别墅买家可以直接在自己的账户里选择装修方案，订单会立即进入店铺。",
    "m5_title": "集团总览",
    "m5_text": "业主的总览页面，三项业务一目了然。售出多少栋别墅，到账多少资金。哪些付款已逾期。礼宾服务和店铺本月收入多少。每位客户在三项业务中带来的收入。金额可按泰铢、美元或人民币显示。",
    "caption_1": "房源。Hillside 19 项目的 19 栋别墅显示在一张平面图上。颜色表示状态，进度条表示施工进度。",
    "caption_2": "中文版买家账户。带照片的施工阶段、已付和待付金额、合同和验收单。",
    "caption_3": "礼宾服务。业主用俄文书写，调度员看到的是泰文翻译。计时器显示需求已等待多久。",
    "caption_4": "店铺。集团工地、施工方和买家的订单集中在一个列表里。每件商品都能看到库存和到货日期。",
    "caption_5": "集团总览。施工、销售、礼宾和店铺集中在一个页面。金额可按泰铢、美元或人民币显示。",
    "caption_link": "打开此页面",
    "roles_title": "每个角色只看到自己的部分",
    "roles_text": "买家只能看到自己的别墅。投资人查看项目汇总。销售经理处理别墅、交易和付款，礼宾调度员处理服务需求。企业所有者可以看到全部内容。在演示中，可通过“查看身份”切换四个角色：合伙人（即所有者）、销售、买家和礼宾。投资人视图属于第一版内容，演示中暂未提供。",
    "journey_title": "买家从预订到交房看到的内容",
    "journey_1": "买下别墅。销售经理登记预订，别墅在平面图上立即显示为已占用。买家收到个人账户的链接。",
    "journey_2": "用自己的语言跟进施工。每个阶段都有照片和简短报告。来自上海的买家看中文，来自莫斯科的买家看俄文。",
    "journey_3": "按阶段付款。账户里写明下一笔付款的金额和截止日期。款项到账后，经理进行确认，收据随即出现在账户中。付款方式与现在相同：系统不收款，只显示付款计划。",
    "journey_4": "在集团的店里选购装修材料和家具。从商品目录中挑选方案，预算即时更新。订单进入店铺，并与他的别墅关联。",
    "journey_5": "交房后使用礼宾服务。机场接机、入住前清洁和小型维修，都在同一个账户里预约。",
    "about_title": "本系统由 demda.pro 工作室开发",
    "about_text": "demda.pro 是一家定制软件开发工作室。创始人 Dmitry Demchenko 自2012年起从事 SAP 相关工作。以下是我们已投入使用的部分作品。",
    "about_fact_1": "MyPulso：我们自己的私人教练服务。客户端和教练端两款应用已在 App Store 和 Google Play 上架。",
    "about_fact_2": "为一家租赁公司开发的运营系统。订单从外部预订系统自动导入。后台管理订单、财务流水和报表。机器人按角色发送通知，司机有自己的应用，已在 App Store 和 Google Play 上架。系统已正式投入运行。",
    "about_fact_3": "Maketa：我们的应用界面设计工具，任何人都可以在 maketa.pro 上使用。",
    "about_link": "在 demda.pro 了解工作室",
    "process_title": "合作流程",
    "process_steps": ["从一个项目开始。我们需要别墅清单、付款计划和几张工地照片。我们会了解目前的销售方式，以及谁需要看到哪些信息。","收到数据两周后，我们展示第一批页面，上面是开发商真实的别墅、买家和付款。展示之后，再核算第一版的价格。","可投入使用的第一版在启动后八周完成。内容包括房源、销售，以及中、英、俄三种语言的买家账户与投资人视图。上线前，中文内容由母语人士审校。","之后接入礼宾服务和店铺。它们使用同一套客户和别墅数据，无需重做。具体时间在第一版完成后确定。"],
    "process_note": "系统部署在亚洲的服务器上。服务器和数据都归开发商所有。",
    "cta_title": "打开演示看看",
    "cta_text": "演示中的每个按钮都可以操作：登记预订、确认付款、把买家账户切换为中文、在店里下单。数据均为虚构，演示可以随时重置。",
    "cta_button": "打开演示",
    "contact": "请发邮件至 hello@demda.pro，或通过 Telegram（@demda）联系 demda.pro 创始人 Dmitry Demchenko。发给我们一个项目，两周后我们在系统里展示给您看。",
    "og_title": "别墅销售、家居建材店和礼宾服务，用一个系统管理",
    "og_description": "买家用自己的语言查看施工和付款。投资人随时了解项目进展。演示支持中文、英文和俄文。",
    "demo_about": "关于系统",
    "demo_contact": "联系我们",
    "footer_note": "demda.pro 演示原型。公司名称、人名和数据均为虚构。照片来自免费图库，并非真实物业。",
    "footer_credits": "照片作者",
    "alt_d_hero": "坐落在山坡上的平顶别墅，带泳池，四周是热带植被",
    "alt_d_biz_build": "施工中的别墅：露出钢筋的墙体，背景是热带植被",
    "alt_d_biz_shop": "装修材料和家具展厅：瓷砖和石材样品架、沙发和灯具",
    "alt_d_biz_service_maid": "客房服务员在别墅卧室里整理床铺",
    "alt_d_biz_service_driver": "司机手持车钥匙站在车旁",
    "alt_d_biz_service_minivan": "机场航站楼外车门敞开的商务车",
    "alt_d_interior": "已完工别墅的客厅，连通露台和泳池，采用木材和石材装饰",
    "alt_d_warehouse": "店铺仓库：摆满纸箱的货架和成托的瓷砖",
    "alt_frame_1": "演示中的“房源”页面：Hillside 19 项目的 19 栋别墅，每栋都显示状态和施工进度条",
    "alt_frame_2": "中文版买家账户：带照片的施工阶段、已付和待付金额",
    "alt_frame_3": "礼宾需求 K-118：机场接机、与业主的对话及消息翻译",
    "alt_frame_4": "店铺“订单”页面：三个渠道的订单，显示状态、金额和到货日期",
    "alt_frame_5": "演示中的集团总览：别墅销售、到账资金、礼宾服务和店铺集中在一个页面",
    "page_title": "Villa Group · 开发商管理系统：介绍",
    "ui_lang": "语言",
    "ui_theme": "主题",
    "ui_theme_system": "跟随系统",
    "ui_theme_light": "浅色",
    "ui_theme_dark": "深色",
    "ui_module": "模块",
    "ui_step": "步骤",
    "ui_home": "demda.pro，回到顶部",
    "meta_desc": "Villa Group：普吉岛开发商管理系统介绍。房源与销售、买家账户、礼宾服务、店铺、合伙人总览。"
  }
  };
  if (typeof module !== "undefined" && module.exports) module.exports = T; else root.VG_TEXTS = T;
})(this);
