/* Сгенерировано tools/import-texts.cjs из 12-teksty-opisaniya.md + служебные строки интерфейса страницы, не из файла копирайтера (page_title, ui_lang, ui_theme, ui_theme_system, ui_theme_light, ui_theme_dark, ui_module, ui_step, ui_home, meta_desc). Руками не править. */
(function (root) {
  var T = {
  "ru": {
    "h1": "Виллы, магазин и консьерж в одной системе",
    "lead": "Покупатель следит за стройкой и платежами на своём языке. Вы видите три бизнеса в одних цифрах.",
    "demo_note": "Villa Group и проект Hillside 19 — названия для демо. В вашей системе будут ваши проекты и ваши данные.",
    "pain_title": "Три бизнеса, одни и те же клиенты",
    "pain_text": "Человек покупает у вас виллу. Потом заказывает в вашем магазине мебель и отделку. После передачи ключей пишет консьержу: встретить в аэропорту, убрать дом, починить кондиционер.\n\nСейчас это три отдельные истории. Платежи записаны на листочке и в таблице. Фото со стройки уходят в чат. Заявки консьержу приходят в личные сообщения, а исполнители отвечают по-тайски. Инвестор из Китая спрашивает, как идёт стройка, и ответ собирают вручную. Сколько один клиент принёс всем трём бизнесам, никто не скажет.",
    "modules_title": "Из чего состоит система",
    "m1_title": "Лоты и продажи",
    "m1_text": "Все виллы проекта на одной схеме: свободна, бронь, продана и сколько построено. У каждого покупателя карточка с графиком платежей по этапам стройки. Сразу видно, какой платёж следующий и какой просрочен. Сделки идут по воронке, от первого звонка до договора. По каждому клиенту записано, кто его привёл: агент, сайт, рекомендация или партнёр в Китае.",
    "m2_title": "Кабинет покупателя и инвестора",
    "m2_text": "Покупатель открывает ссылку и видит свою виллу. Там этапы стройки с фото и отчётами, сколько оплачено и сколько осталось, договоры и акты. Кабинет работает на русском, английском и китайском, язык покупатель выбирает сам. Инвестор видит сводку по всему проекту: сколько вилл продано, сколько денег пришло, на каком этапе стройка.",
    "m3_title": "Консьерж",
    "m3_text": "Владелец виллы оставляет заявку: встреча в аэропорту, трансфер, уборка, ремонт. Диспетчер назначает исполнителя и видит, сколько времени заявка ждёт ответа. Переписка переводится сама. Владелец пишет по-русски или по-китайски, исполнитель читает по-тайски. Когда работа сделана, владелец получает счёт.",
    "m4_title": "Магазин мебели и отделки",
    "m4_text": "Магазин работает как отдельный бизнес. В каталоге отделка, сантехника, кухни, мебель, свет и текстиль. По каждой позиции видно, сколько лежит на складе и что везут под заказ. Цены две: розничная и для партнёров. Заказы трёх видов: на ваши стройки, от других застройщиков и подрядчиков, от покупателей и владельцев вилл. У каждой поставки свой срок, выручка считается по каждому виду заказов. Покупатель виллы выбирает отделку прямо в своём кабинете, и заказ сразу попадает в магазин.",
    "m5_title": "Сводка партнёра",
    "m5_text": "Три бизнеса на одном экране. Сколько вилл продано и сколько денег пришло. Какие платежи просрочены. Сколько за месяц заработали консьерж и магазин. Отдельно видно, сколько каждый клиент принёс всем трём бизнесам. Суммы показываются в батах, долларах или юанях.",
    "journey_title": "Что видит покупатель от брони до ключей",
    "journey_1": "Покупает виллу. Менеджер ставит бронь, и вилла на схеме становится занятой. Покупатель получает ссылку на свой кабинет.",
    "journey_2": "Следит за стройкой на своём языке. У каждого этапа фото и короткий отчёт. Покупатель из Шанхая читает по-китайски, из Москвы по-русски.",
    "journey_3": "Платит по этапам. В кабинете видно, сколько платить дальше и до какого числа. Деньги пришли — менеджер отмечает платёж, и в кабинете появляется квитанция. Сами деньги идут как сейчас: система их не принимает, она показывает график.",
    "journey_4": "Выбирает отделку и мебель в вашем магазине. Варианты берёт из каталога, смета пересчитывается сразу. Заказ уходит в магазин и привязан к его вилле.",
    "journey_5": "Получает ключи и пользуется консьержем. Встречу в аэропорту, уборку перед приездом и мелкий ремонт заказывает из того же кабинета.",
    "process_title": "Как пойдёт работа",
    "process_steps": ["Берём один ваш проект. Нужны список вилл, графики оплат и несколько фото со стройки. Разбираемся, как вы продаёте сейчас и кто что должен видеть.","Через две недели после получения данных показываем первые экраны. На них ваши виллы, ваши покупатели и ваши платежи. После показа считаем цену первой версии.","Первая версия, на которой можно работать, готова через 8 недель от начала. В неё входят лоты, продажи и кабинет покупателя и инвестора на трёх языках. Китайские тексты кабинета до запуска вычитывает носитель языка.","Потом подключаем консьержа и магазин. Они встают на ту же базу клиентов и вилл, переделывать ничего не придётся."],
    "process_note": "Систему ставим на сервер в Азии. Сервер ваш, данные тоже ваши.",
    "cta_title": "Откройте демо и покажите партнёрам",
    "cta_text": "В демо работает каждая кнопка. Можно поставить бронь, отметить платёж, переключить кабинет на китайский, собрать заказ в магазине. Данные выдуманы, демо можно сбросить в любой момент.",
    "cta_button": "Открыть демо",
    "contact": "Пишите Дмитрию в Telegram @demda или на почту hello@demda.pro. Пришлите один проект, и через две недели покажем его в системе.",
    "caption_1": "Лоты. Все 19 вилл Hillside 19 на одной схеме. Цвет показывает статус, полоса показывает, сколько построено.",
    "caption_2": "Кабинет покупателя на китайском. Этапы стройки с фото, оплачено и осталось, договоры и акты.",
    "caption_3": "Консьерж. Владелец и диспетчер переписываются в одном чате, сообщения переводятся. Таймер показывает, сколько заявка ждёт ответа.",
    "caption_4": "Магазин. Заказы своих строек, подрядчиков и покупателей в одном списке. У каждой позиции видно склад и срок поставки.",
    "caption_5": "Сводка партнёра. Стройка, продажи, консьерж и магазин на одном экране. Суммы в батах, долларах или юанях.",
    "topbar_name": "demda.pro · система для застройщика",
    "biz_build": ["Застройка","Виллы на продажу"],
    "biz_shop": ["Магазин","Мебель и отделка"],
    "biz_service": ["Консьерж","Трансфер, уборка, ремонт"],
    "footer_note": "Прототип demda.pro. Названия компаний, имена людей и цифры вымышлены. Фото взяты из открытых фотобанков и не изображают реальные объекты.",
    "footer_credits": "Авторы фото",
    "alt_d_hero": "Готовая вилла с плоской кровлей и бассейном на склоне холма, вокруг тропическая зелень",
    "alt_d_biz_build": "Стройка виллы: бетонный каркас в лесах, арматура, вокруг тропическая зелень",
    "alt_d_biz_shop": "Шоурум отделки и мебели: стенд с образцами плитки и камня, диван и светильник",
    "alt_d_biz_service_driver": "Водитель держит ключи у машины",
    "alt_d_biz_service_minivan": "Минивэн с открытой дверью у терминала аэропорта",
    "alt_d_biz_service_maid": "Горничная заправляет кровать в спальне виллы",
    "alt_d_interior": "Гостиная готовой виллы с выходом на террасу и бассейн, отделка из дерева и камня",
    "alt_d_warehouse": "Склад магазина: стеллажи с коробками и паллеты с плиткой",
    "alt_frame_1": "Экран «Лоты» в демо: 19 вилл проекта Hillside 19, у каждой статус и полоса готовности стройки",
    "alt_frame_2": "Кабинет покупателя на китайском: этапы стройки с фото, сколько оплачено и сколько осталось",
    "alt_frame_3": "Заявка К-118 в консьерже: встреча в аэропорту, переписка с владельцем и перевод сообщений",
    "alt_frame_4": "Экран «Заказы» магазина: заказы трёх каналов со статусом, суммой и сроком поставки",
    "alt_frame_5": "Сводка партнёра в демо: продажи вилл, поступления, консьерж и магазин на одном экране",
    "deal_stages": ["Новый лид","Квалификация","Показ","Бронь","Договор"],
    "shop_channels": ["Свои стройки","Застройщики и подрядчики","Розница"],
    "page_title": "Villa Group · система для застройщика: описание",
    "ui_lang": "Язык",
    "ui_theme": "Тема",
    "ui_theme_system": "Как в системе",
    "ui_theme_light": "Светлая",
    "ui_theme_dark": "Тёмная",
    "ui_module": "Модуль",
    "ui_step": "Шаг",
    "ui_home": "demda.pro, наверх",
    "meta_desc": "Villa Group: описание системы для застройщика на Пхукете. Лоты и продажи, кабинет покупателя, консьерж, магазин, сводка партнёра."
  },
  "en": {
    "h1": "Your villas, store and concierge in one system",
    "lead": "Buyers follow construction and payments in their own language. You see all three businesses in one set of numbers.",
    "demo_note": "Villa Group and Hillside 19 are demo names. Your system will run on your own projects and data.",
    "pain_title": "Three businesses, the same clients",
    "pain_text": "A client buys a villa from you. Later they order furniture and finishes from your store. After handover they message the concierge: an airport pickup, cleaning, a broken air conditioner.\n\nRight now these are three separate stories. Payments are tracked on paper and in spreadsheets. Site photos go into a chat. Concierge requests arrive as personal messages, and the staff reply in Thai. When an investor in China asks how construction is going, someone pulls the answer together by hand. Nobody can tell how much one client has brought to all three businesses.",
    "modules_title": "What the system is made of",
    "m1_title": "Units and sales",
    "m1_text": "Every villa in the project on one plan: available, reserved, sold, and how far construction has gone. Each buyer has a card with a payment schedule tied to construction stages. You see at a glance which payment is next and which is overdue. Deals move through a pipeline from the first call to the signed contract. For every client you know who brought them in: an agent, the website, a referral or a partner in China.",
    "m2_title": "Buyer and investor portal",
    "m2_text": "A buyer opens a link and sees their villa. Construction stages with photos and reports, what has been paid and what is left, contracts and stage acceptance certificates. The portal works in Russian, English and Chinese, and the buyer picks the language. Investors get a summary of the whole project: villas sold, money received, current construction stage.",
    "m3_title": "Concierge",
    "m3_text": "A villa owner sends a request: airport pickup, transfer, cleaning, repairs. The dispatcher assigns someone and sees how long the request has been waiting. Messages are translated automatically. The owner writes in Russian or Chinese, the staff member reads it in Thai. When the job is done, the owner gets an invoice.",
    "m4_title": "Furniture and finishes store",
    "m4_text": "The store runs as a business of its own. The catalog covers finishes, plumbing, kitchens, furniture, lighting and textiles. For every item you see what is in stock and what is on order. There are two prices: retail and partner. Orders come in three kinds: for your own construction sites, from other developers and contractors, and from buyers and villa owners. Every delivery has a date, and revenue is counted for each kind of order. A villa buyer picks finishes right in their portal, and the order goes straight to the store.",
    "m5_title": "Partner dashboard",
    "m5_text": "All three businesses on one screen. Villas sold and money received. Overdue payments. What the concierge and the store earned this month. You also see what each client has brought to all three businesses. Amounts can be shown in baht, dollars or yuan.",
    "journey_title": "What a buyer sees, from reservation to keys",
    "journey_1": "Buys a villa. The sales manager records the reservation, and the villa shows as taken on the plan. The buyer gets a link to their portal.",
    "journey_2": "Follows construction in their own language. Every stage has photos and a short report. A buyer from Shanghai reads it in Chinese, a buyer from Moscow in Russian.",
    "journey_3": "Pays stage by stage. The portal shows the next amount and the due date. Once the money arrives, the manager marks the payment and a receipt appears in the portal. Payments go the way they do now: the system doesn't take money, it shows the schedule.",
    "journey_4": "Chooses finishes and furniture from your store. Options come from the catalog, and the estimate updates instantly. The order goes to the store, linked to their villa.",
    "journey_5": "Gets the keys and uses the concierge. Airport pickup, cleaning before arrival and small repairs are booked from the same portal.",
    "process_title": "How we'll work",
    "process_steps": ["We start with one of your projects. We need the villa list, payment schedules and a few site photos. We look at how you sell today and who needs to see what.","Two weeks after we get the data, we show the first screens. Your villas, your buyers, your payments. After that review we price the first version.","The first working version is ready eight weeks from the start. It covers units, sales and the buyer and investor portal in three languages. A native speaker proofreads the Chinese portal text before launch.","Then we add the concierge and the store. They sit on the same client and villa data, so nothing has to be rebuilt."],
    "process_note": "The system runs on a server in Asia. The server is yours, and so is the data.",
    "cta_title": "Open the demo and show it to your partners",
    "cta_text": "Every button in the demo works. Reserve a villa, mark a payment, switch the portal to Chinese, put together a store order. The data is made up, and you can reset the demo at any time.",
    "cta_button": "Open the demo",
    "contact": "Message Dmitry on Telegram at @demda or email hello@demda.pro. Send us one project, and two weeks later we'll show it to you in the system.",
    "caption_1": "Units. All 19 villas of Hillside 19 on one plan. Color shows the status, the bar shows construction progress.",
    "caption_2": "Buyer portal in Chinese. Construction stages with photos, paid and outstanding, contracts and certificates.",
    "caption_3": "Concierge. The owner and the dispatcher share one chat, and messages are translated. A timer shows how long the request has been waiting.",
    "caption_4": "Store. Orders from your own sites, contractors and buyers in one list. Stock and delivery date for every item.",
    "caption_5": "Partner dashboard. Construction, sales, concierge and store on one screen. Amounts in baht, dollars or yuan.",
    "topbar_name": "demda.pro · a system for villa developers",
    "biz_build": ["Construction","Villas for sale"],
    "biz_shop": ["Store","Furniture and finishes"],
    "biz_service": ["Concierge","Pickups, cleaning, repairs"],
    "footer_note": "A demda.pro prototype. Company names, people and figures are made up. Photos come from free stock libraries and do not show real properties.",
    "footer_credits": "Photo credits",
    "alt_d_hero": "Finished villa with a flat roof and a pool on a hillside, surrounded by tropical greenery",
    "alt_d_biz_build": "Villa under construction: concrete frame in scaffolding, rebar, tropical greenery around",
    "alt_d_biz_shop": "Finishes and furniture showroom: a stand of tile and stone samples, a sofa and a lamp",
    "alt_d_biz_service_driver": "Driver holding the car keys next to the car",
    "alt_d_biz_service_minivan": "Minivan with an open door outside the airport terminal",
    "alt_d_biz_service_maid": "Housekeeper making the bed in a villa bedroom",
    "alt_d_interior": "Living room of a finished villa opening onto a terrace and pool, with wood and stone finishes",
    "alt_d_warehouse": "Store warehouse: shelves of boxes and pallets of tiles",
    "alt_frame_1": "Units screen in the demo: the 19 villas of Hillside 19, each with its status and construction progress bar",
    "alt_frame_2": "Buyer portal in Chinese: construction stages with photos, amount paid and amount outstanding",
    "alt_frame_3": "Concierge request K-118: airport pickup, chat with the owner and message translation",
    "alt_frame_4": "Store orders screen: orders from three channels with status, amount and delivery date",
    "alt_frame_5": "Partner dashboard in the demo: villa sales, money received, concierge and store on one screen",
    "deal_stages": ["New lead","Qualified","Viewing","Reserved","Contract"],
    "shop_channels": ["Own projects","Developers & contractors","Retail"],
    "page_title": "Villa Group · a system for developers: overview",
    "ui_lang": "Language",
    "ui_theme": "Theme",
    "ui_theme_system": "Match system",
    "ui_theme_light": "Light",
    "ui_theme_dark": "Dark",
    "ui_module": "Module",
    "ui_step": "Step",
    "ui_home": "demda.pro, back to top",
    "meta_desc": "Villa Group: an overview of a system for a Phuket developer. Units and sales, buyer portal, concierge, store, partner dashboard."
  },
  "zh": {
    "h1": "别墅、家居建材和礼宾服务，一套系统管理",
    "lead": "买家用自己的语言查看施工进度和付款情况。您在同一组数据中掌握三项业务。",
    "demo_note": "Villa Group 和 Hillside 19 为演示名称。正式系统将使用您自己的项目和数据。",
    "pain_title": "三项业务，同一批客户",
    "pain_text": "客户从您这里买下一栋别墅。之后，他在您的店里订购家具和装修材料。交房后，他联系礼宾服务：机场接机、打扫房屋、修理空调。\n\n现在这是三件互不相关的事。付款记在纸上和表格里。工地照片发在聊天群里。礼宾需求通过私信传来，工作人员用泰语回复。中国的投资人询问工程进度时，只能有人手工整理答复。一个客户在三项业务中一共带来多少收入，没有人说得清。",
    "modules_title": "系统由哪些部分组成",
    "m1_title": "房源与销售",
    "m1_text": "项目中的所有别墅显示在一张平面图上：可售、已预订、已售出，以及施工进度。每位买家都有一张客户卡，附有按施工阶段划分的付款计划。下一笔付款和逾期付款一目了然。交易按销售流程推进，从第一次咨询到签订合同。每位客户的来源都有记录：中介、网站、熟人推荐或中国合作伙伴。",
    "m2_title": "买家与投资人账户",
    "m2_text": "买家打开链接，就能看到自己的别墅：各施工阶段的照片和报告、已付和待付金额、合同和阶段验收单。账户支持中文、英文和俄文，买家可自行选择。投资人可以查看整个项目的汇总：已售出多少栋、到账多少资金、施工进行到哪个阶段。",
    "m3_title": "礼宾服务",
    "m3_text": "业主提交需求：机场接机、接送、清洁、维修。调度员指派工作人员，并能看到需求已经等待了多久。对话自动翻译：业主用中文或俄文书写，工作人员看到的是泰文。服务完成后，业主收到账单。",
    "m4_title": "家具与装修材料店",
    "m4_text": "店铺作为一项独立业务运营。商品目录包括装修材料、卫浴、厨房、家具、灯具和布艺。每件商品都能看到现有库存和在途订货。价格分为零售价和合作伙伴价。订单分三类：自有工地、其他开发商和承包商、买家和别墅业主。每批供货都有明确日期，收入按订单类型分别统计。别墅买家可以直接在自己的账户里选择装修方案，订单会立即进入店铺。",
    "m5_title": "合伙人总览",
    "m5_text": "三项业务集中在一个页面上。售出多少栋别墅，到账多少资金。哪些付款已逾期。礼宾服务和店铺本月收入多少。还能看到每位客户在三项业务中带来的收入。金额可按泰铢、美元或人民币显示。",
    "journey_title": "买家从预订到交房看到的内容",
    "journey_1": "买下别墅。销售经理登记预订，别墅在平面图上立即显示为已占用。买家收到个人账户的链接。",
    "journey_2": "用自己的语言跟进施工。每个阶段都有照片和简短报告。来自上海的买家看中文，来自莫斯科的买家看俄文。",
    "journey_3": "按阶段付款。账户里写明下一笔付款的金额和截止日期。款项到账后，经理进行确认，收据随即出现在账户中。付款方式与现在相同：系统不收款，只显示付款计划。",
    "journey_4": "在您的店里选购装修材料和家具。从商品目录中挑选方案，预算即时更新。订单进入店铺，并与他的别墅关联。",
    "journey_5": "交房后使用礼宾服务。机场接机、入住前清洁和小型维修，都在同一个账户里预约。",
    "process_title": "合作流程",
    "process_steps": ["从您的一个项目开始。我们需要别墅清单、付款计划和几张工地照片。我们会了解您目前的销售方式，以及谁需要看到哪些信息。","收到数据两周后，我们展示第一批页面，上面是您的别墅、您的买家和您的付款。展示之后，我们核算第一版的价格。","可投入使用的第一版在启动后八周完成。内容包括房源、销售，以及中、英、俄三种语言的买家与投资人账户。上线前，账户的中文内容由母语人士审校。","之后接入礼宾服务和店铺。它们使用同一套客户和别墅数据，无需重做。"],
    "process_note": "系统部署在亚洲的服务器上。服务器归您所有，数据也归您所有。",
    "cta_title": "打开演示，与合作伙伴一起查看",
    "cta_text": "演示中的每个按钮都可以操作：登记预订、确认付款、把账户切换为中文、在店里下单。数据均为虚构，演示可以随时重置。",
    "cta_button": "打开演示",
    "contact": "请发邮件至 hello@demda.pro，或通过 Telegram（@demda）联系 Dmitry。发给我们一个项目，两周后我们在系统里展示给您看。",
    "caption_1": "房源。Hillside 19 项目的 19 栋别墅显示在一张平面图上。颜色表示状态，进度条表示施工进度。",
    "caption_2": "中文版买家账户。带照片的施工阶段、已付和待付金额、合同和验收单。",
    "caption_3": "礼宾服务。业主和调度员在同一个对话里交流，消息自动翻译。计时器显示需求已等待多久。",
    "caption_4": "店铺。自有工地、承包商和买家的订单集中在一个列表里。每件商品都能看到库存和到货日期。",
    "caption_5": "合伙人总览。施工、销售、礼宾和店铺集中在一个页面。金额可按泰铢、美元或人民币显示。",
    "topbar_name": "demda.pro · 别墅开发商管理系统",
    "biz_build": ["别墅开发","在售别墅"],
    "biz_shop": ["家居建材店","家具与装修材料"],
    "biz_service": ["礼宾服务","接送、清洁、维修"],
    "footer_note": "demda.pro 演示原型。公司名称、人名和数据均为虚构。照片来自免费图库，并非真实物业。",
    "footer_credits": "照片作者",
    "alt_d_hero": "坐落在山坡上的平顶别墅，带泳池，四周是热带植被",
    "alt_d_biz_build": "施工中的别墅：脚手架包围的混凝土框架和钢筋，四周是热带植被",
    "alt_d_biz_shop": "装修材料和家具展厅：瓷砖和石材样品架、沙发和灯具",
    "alt_d_biz_service_driver": "司机手持车钥匙站在车旁",
    "alt_d_biz_service_minivan": "机场航站楼外车门敞开的商务车",
    "alt_d_biz_service_maid": "客房服务员在别墅卧室里整理床铺",
    "alt_d_interior": "已完工别墅的客厅，连通露台和泳池，采用木材和石材装饰",
    "alt_d_warehouse": "店铺仓库：摆满纸箱的货架和成托的瓷砖",
    "alt_frame_1": "演示中的“房源”页面：Hillside 19 项目的 19 栋别墅，每栋都显示状态和施工进度条",
    "alt_frame_2": "中文版买家账户：带照片的施工阶段、已付和待付金额",
    "alt_frame_3": "礼宾需求 K-118：机场接机、与业主的对话及消息翻译",
    "alt_frame_4": "店铺“订单”页面：三个渠道的订单，显示状态、金额和到货日期",
    "alt_frame_5": "演示中的合伙人总览：别墅销售、到账资金、礼宾服务和店铺集中在一个页面",
    "deal_stages": ["新线索","需求确认","带看","预订","签约"],
    "shop_channels": ["自有工地","开发商和承包商","零售"],
    "page_title": "Villa Group · 开发商管理系统：介绍",
    "ui_lang": "语言",
    "ui_theme": "主题",
    "ui_theme_system": "跟随系统",
    "ui_theme_light": "浅色",
    "ui_theme_dark": "深色",
    "ui_module": "模块",
    "ui_step": "步骤",
    "ui_home": "demda.pro，回到顶部",
    "meta_desc": "Villa Group：普吉岛开发商管理系统介绍。房源与销售、买家账户、礼宾服务、店铺、合伙人总览。"
  }
  };
  if (typeof module !== "undefined" && module.exports) module.exports = T; else root.VG_TEXTS = T;
})(this);
